name: Deploy Hugo site to S3

on: push

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install Hugo
        run: |
          HUGO_DOWNLOAD=hugo_extended_${HUGO_VERSION}_Linux-64bit.tar.gz
          wget https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/${HUGO_DOWNLOAD}
          tar xvzf ${HUGO_DOWNLOAD} hugo
          mv hugo $HOME/hugo
        env:
          HUGO_VERSION: 0.113.0

      - name: Update config.yaml with secrets
        run: |
          sed -i 's|S3_BUCKET_URL_PLACEHOLDER|${{ secrets.S3_BUCKET_URL }}|g' config.yaml
          sed -i 's|AWS_REGION_PLACEHOLDER|${{ secrets.AWS_REGION }}|g' config.yaml

      - name: Hugo Build
        run: $HOME/hugo -v

      - name: Debug:Print AWS Bucket Info
        run: |
          echo "S3_BUCKET_URL: ${{ secrets.S3_BUCKET_URL }}"
          BUCKET_NAME=$(echo ${{ secrets.S3_BUCKET_URL }} | cut -d '/' -f 1)
          REGION=$(echo ${{ secrets.S3_BUCKET_URL }} | cut -d '/' -f 2)
          echo "Parsed BUCKET_NAME: ${BUCKET_NAME}"
          echo "Parsed REGION: ${REGION}"
          aws s3 ls s3://${BUCKET_NAME}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Deploy to S3
        if: github.ref == 'refs/heads/main'
        run: |
          BUCKET_NAME=$(echo ${{ secrets.S3_BUCKET_URL }} | cut -d '/' -f 1)
          aws s3 sync ./public s3://${BUCKET_NAME} --delete --exact-timestamps
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
