name: Deploy Hugo site to S3

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Hugo
        run: |
          HUGO_DOWNLOAD=hugo_extended_${HUGO_VERSION}_Linux-64bit.tar.gz
          wget https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/${HUGO_DOWNLOAD}
          tar xvzf ${HUGO_DOWNLOAD} hugo
          sudo mv hugo /usr/local/bin/
        env:
          HUGO_VERSION: 0.113.0

      - name: Build Hugo site
        run: hugo

      - name: Install AWS CLI
        run: |
          curl "https://d1uj6qtbmh3dt5.cloudfront.net/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install

      - name: Set up AWS CLI
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set region ${REGION}
        env:
          REGION: "us-east-1"  # Specify the region if not part of the bucket name

      - name: Deploy to S3
        run: |
          # Extract bucket name from the S3_BUCKET_NAME secret
          BUCKET_NAME=${{ secrets.S3_BUCKET_NAME }}

          # Sync files to S3
          aws s3 sync ./public s3://${BUCKET_NAME} --delete --exact-timestamps
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          REGION: "us-east-1"  # Specify the region if not part of the bucket name
