name: Deploy Hugo site to S3

on: push

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install Hugo
        run: |
          HUGO_DOWNLOAD=hugo_extended_${HUGO_VERSION}_Linux-64bit.tar.gz
          wget https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/${HUGO_DOWNLOAD}
          tar xvzf ${HUGO_DOWNLOAD} hugo
          mv hugo $HOME/hugo
        env:
          HUGO_VERSION: 0.113.0
      - name: Hugo Build
        run: $HOME/hugo -v
      - name: Deploy to S3
        if: github.ref == 'refs/heads/main'
        run: |
          # Extract bucket name and region from the AWS_S3_BUCKET secret
          BUCKET_NAME=$(echo ${{ secrets.AWS_S3_BUCKET }} | cut -d '/' -f 1)
          REGION=$(echo ${{ secrets.AWS_S3_BUCKET }} | cut -d '/' -f 2)
          
          # Set AWS CLI profile
          aws configure set profile default aws_access_key_id=$AWS_ACCESS_KEY_ID aws_secret_access_key=$AWS_SECRET_ACCESS_KEY
          
          # Run Hugo deploy command
          $HOME/hugo -v deploy --maxDeletes -1 --force --target=aws-s3-bucket
          
          # Sync only new files
          aws s3 sync ./public s3://${BUCKET_NAME} --delete --exact-timestamps
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
